/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HttpServerPnl.java
 *
 * Created on 2014-2-25, 17:20:07
 */
package cptools.httpserver;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author zhangwei <laketea@163.com>
 */
public class HttpServerPnl extends javax.swing.JPanel {

    public static Log logger;
    HttpServer server;

    /** Creates new form HttpServerPnl */
    public HttpServerPnl() {
        initComponents();
        logger = new Log(this.jtxCmd);
    }

    private void startHttpServer() {
        server = new HttpServer();
        try {
             (new Thread(server)).start();
        } catch (Exception ex) {
            Logger.getLogger(HttpServerPnl.class.getName()).log(Level.SEVERE, null, ex);
            logger.logln(ex.getMessage());
        }
        this.jbtStart.setEnabled(false);
        this.jbtStop.setEnabled(true);
    }

    private void stopHttpServer() {
        if (this.server != null) {
            try {
                this.server.stop();

            } catch (Exception ex) {
                Logger.getLogger(HttpServerPnl.class.getName()).log(Level.SEVERE, null, ex);
                logger.logln(ex.getMessage());
            }
            this.jbtStart.setEnabled(true);
            this.jbtStop.setEnabled(false);
        }

    }

    private void clearJtx() {
        this.jtxCmd.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtStart = new javax.swing.JButton();
        jbtStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxCmd = new javax.swing.JTextArea();
        jtbClear = new javax.swing.JButton();

        jbtStart.setText("启动HttpServer");
        jbtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtStartActionPerformed(evt);
            }
        });

        jbtStop.setText("关闭HttpServer");
        jbtStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtStopActionPerformed(evt);
            }
        });

        jLabel1.setText("绑定端口为:3838");

        jtxCmd.setColumns(20);
        jtxCmd.setRows(5);
        jScrollPane1.setViewportView(jtxCmd);

        jtbClear.setText("清屏");
        jtbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbClearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jbtStart)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtStop)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 105, Short.MAX_VALUE)
                .add(jtbClear)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtStart)
                    .add(jbtStop)
                    .add(jLabel1)
                    .add(jtbClear))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtStartActionPerformed
        // TODO add your handling code here:
        startHttpServer();
    }//GEN-LAST:event_jbtStartActionPerformed

    private void jtbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbClearActionPerformed
        // TODO add your handling code here:
        clearJtx();
    }//GEN-LAST:event_jtbClearActionPerformed

    private void jbtStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtStopActionPerformed
        // TODO add your handling code here:
        this.stopHttpServer();
    }//GEN-LAST:event_jbtStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtStart;
    private javax.swing.JButton jbtStop;
    private javax.swing.JButton jtbClear;
    private javax.swing.JTextArea jtxCmd;
    // End of variables declaration//GEN-END:variables
}
