/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComboPnl.java
 *
 * Created on 2013-12-2, 17:10:15
 */
package cptools.combo;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author zhangwei <laketea@163.com>
 */
public class ComboPnl extends javax.swing.JPanel {

    /** Creates new form ComboPnl */
    public ComboPnl() {
        initComponents();
        StreamCombo.setTextArea(this.jtxConsole);
    }
    
    public String getPath(){
        return this.jtfPath.getText();
    }
    
    private String selectDirectoryDialog() {
        String path = "";
        String name = "";
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//        chooser.setCurrentDirectory(new File(path));
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        int retval = chooser.showOpenDialog(this);//显示“打开文件”对话框
        if (retval == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            name = file.getName();
            path = file.getAbsolutePath();
        }
        return path;
    }
    
    public void execute(String cmd){
        String path = this.getPath();
        if(path==null || "".equals(path)){
            JOptionPane.showMessageDialog(this, "ANT路径不能为空！");
            return ;
        }
        new Thread(new ComboShell(cmd,path)).start();
        this.info("");
    }
    
    public void execute2(String cmd){
        String path = this.getPath();
        if(path==null || "".equals(path)){
            JOptionPane.showMessageDialog(this, "ANT路径不能为空！");
            return ;
        }
        new Thread(new ComboShell(cmd,path+"/build-tools/")).start();
    }
    
    private void info(String info){
        this.jblInfo.setText("注意事项: "+info);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        testjpl = new javax.swing.JPanel();
        jbtDebug = new javax.swing.JButton();
        jbtPublish = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxConsole = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jbtMin = new javax.swing.JButton();
        jbtUnMin = new javax.swing.JButton();
        jblInfo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("设置ant目录:");

        jtfPath.setText("/Users/yfcd/gitrepo/yfui/tools/build-xml/build-tools");

        jButton1.setText("..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("清空输出");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 534, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton8)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtfPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1)
                    .add(jButton8))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        testjpl.setBorder(javax.swing.BorderFactory.createTitledBorder("全局模式设定"));
        testjpl.setToolTipText("");

        jbtDebug.setText("调试模式");
        jbtDebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDebugActionPerformed(evt);
            }
        });

        jbtPublish.setText("发布模式");
        jbtPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPublishActionPerformed(evt);
            }
        });

        jButton11.setText("重编译所有前端工程");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout testjplLayout = new org.jdesktop.layout.GroupLayout(testjpl);
        testjpl.setLayout(testjplLayout);
        testjplLayout.setHorizontalGroup(
            testjplLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testjplLayout.createSequentialGroup()
                .add(jbtDebug)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtPublish)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 439, Short.MAX_VALUE)
                .add(jButton11)
                .addContainerGap())
        );
        testjplLayout.setVerticalGroup(
            testjplLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testjplLayout.createSequentialGroup()
                .add(testjplLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtDebug)
                    .add(jbtPublish)
                    .add(jButton11))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("快捷操作"));

        jButton5.setText("各独立模块合并JS文件");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("生成全局依赖关系");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("启用JS动态合并");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("关闭JS动态合并");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton5)
                    .add(jButton3)
                    .add(jButton4))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jtxConsole.setColumns(20);
        jtxConsole.setRows(5);
        jScrollPane1.setViewportView(jtxConsole);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("压缩文件模式"));

        jbtMin.setText("开启");
        jbtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMinActionPerformed(evt);
            }
        });

        jbtUnMin.setText("关闭");
        jbtUnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUnMinActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jbtMin)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtUnMin)
                .addContainerGap(659, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtMin)
                    .add(jbtUnMin))
                .addContainerGap(3, Short.MAX_VALUE))
        );

        jblInfo.setForeground(new java.awt.Color(204, 0, 0));
        jblInfo.setText("注意事项：");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(testjpl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jblInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(testjpl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jblInfo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path = this.selectDirectoryDialog();
        if(path==null || "".equals(path)){
            JOptionPane.showMessageDialog(this, "ANT路径不能为空！");
        }else{
            this.jtfPath.setText(path);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //生成全局依赖关系
        this.execute("../../ant/bin/ant -file global-deps.xml");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //启动动态JS合并
        this.execute("../../ant/bin/ant -file dync-combo.xml combine-enable");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         //关闭动态JS合并
        this.execute("../../ant/bin/ant -file dync-combo.xml combine-unable");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         //生成各模块静态JS文件
        this.execute("../../ant/bin/ant -file static-combo.xml ");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.jtxConsole.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtDebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDebugActionPerformed
        // TODO add your handling code here:
        //调试模式
        this.execute("../../ant/bin/ant -file pattern-tools.xml set-debug-model");
        this.info("开启调试模式后，如需所有模块立即生效，请点击重编译所有工程!");
        this.jbtDebug.setEnabled(false);
        this.jbtPublish.setEnabled(true);
    }//GEN-LAST:event_jbtDebugActionPerformed

    private void jbtPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPublishActionPerformed
        // TODO add your handling code here:
         //发布模式
        this.execute("../../ant/bin/ant -file pattern-tools.xml set-publish-model");
        this.info("开启发布模式后，如需所有模块立即生效，请点击重编译所有工程!");
        this.jbtDebug.setEnabled(true);
        this.jbtPublish.setEnabled(false);
    }//GEN-LAST:event_jbtPublishActionPerformed

    private void jbtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMinActionPerformed
        // TODO add your handling code here:
        //开启压缩
        this.execute("../../ant/bin/ant -file pattern-tools.xml set-min-model");
        this.info("开启压缩模式后，如未编译min js/css 文件，请点击重编译所有工程!");
        this.jbtMin.setEnabled(false);
        this.jbtUnMin.setEnabled(true);
    }//GEN-LAST:event_jbtMinActionPerformed

    private void jbtUnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUnMinActionPerformed
        // TODO add your handling code here:
        //关闭压缩
        this.execute("../../ant/bin/ant -file pattern-tools.xml set-un-min-model");
        this.jbtMin.setEnabled(true);
        this.jbtUnMin.setEnabled(false);
    }//GEN-LAST:event_jbtUnMinActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your hsandling code here:
         //重编译所有工程
        this.execute("../../ant/bin/ant -file pattern-tools.xml rebuild-all-projects");
    }//GEN-LAST:event_jButton11ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblInfo;
    private javax.swing.JButton jbtDebug;
    private javax.swing.JButton jbtMin;
    private javax.swing.JButton jbtPublish;
    private javax.swing.JButton jbtUnMin;
    private javax.swing.JTextField jtfPath;
    private javax.swing.JTextArea jtxConsole;
    private javax.swing.JPanel testjpl;
    // End of variables declaration//GEN-END:variables
}
