/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsolePnl.java
 *
 * Created on 2013-8-26, 15:54:51
 */
package cptools.ui;

import javax.swing.JTextArea;

/**
 *
 * @author zhangwei <laketea@163.com>
 */
public class ConsolePnl extends javax.swing.JPanel {

    /** Creates new form ConsolePnl */
    public ConsolePnl() {
        initComponents();
        this.output.setLineWrap(true);
    }
    
    
    public JTextArea getTextArea(){
        return this.output;
    }
    
    public void clearTextArea(){
        this.output.setText("");
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
